farmpower/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("registration.urls", namespace="registration")),
    path("", include("sitepages.urls", namespace="sitepages")),
    path("", include("payments.urls", namespace="payments")),
    path("", include("withdrawal.urls", namespace="withdrawal")),
    path('',include("machine.urls",namespace="machine")),
    path('',include("income.urls",namespace="income")),
]

income/urls.py
from django.urls import path
from .views import *

app_name = "income"
urlpatterns = [
    path("receive/120.00/", earnbutton_click1, name="button"),
    path("receive/250.00/", earnbutton_click2, name="button"),
    path("receive/540.00/", earnbutton_click3, name="button"),
    path("receive/950.00/", earnbutton_click4, name="button"),
    path("receive/1830.00/", earnbutton_click5, name="button"),
    path("ref-income/",ref_income,name="ref_income")
]

payments/urls.py
from django.urls import path
from .views import * 
app_name="payments"
urlpatterns = [
	path('initiate-payment/',initiate_payment, name='initiate_payment'),
	path('verify_payment/<str:ref>',verifypayment, name='verifypayment'),
    path('rechargerecord/',rechargerec,name='rechargerec'),
]

payments/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import secrets
from .paystack import Paystack
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class UserWallet(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    currency = models.CharField(max_length=50, default="NGN")
    balance = models.PositiveIntegerField(default=200)
    created_at = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.user.__str__()

    @receiver(post_save, sender=User)
    def create_user_wallet(sender, instance, created, **kwargs):
        if created:
            UserWallet.objects.create(user=instance)


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.PositiveIntegerField()
    ref = models.CharField(max_length=200)
    email = models.EmailField()
    verified = models.BooleanField(default="False")
    date_created = models.DateTimeField(auto_now_add="True")

    class Meta:
        ordering = ("-date_created",)

    def __str__(self):
        return f"Payment: {self.amount}"

    def save(self, *args, **kwargs):
        while not self.ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_ref = Payment.objects.filter(ref=ref)
            if not object_with_similar_ref:
                self.ref = ref

        super().save(*args, **kwargs)

    def amount_value(self):
        return int(self.amount) * 100

    def verifypayment(self):
        paystack = Paystack()
        status, result = paystack.verifypayment(self.ref, self.amount)
        if status:
            if result["amount"] / 100 == self.amount:
                self.verified = True
            self.save()
        if self.verified:
            return True
        return False

withdrawal/models.py
from django.contrib.auth.models import User
from django.db import models

class Withdrawal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    withdrawal_amount = models.DecimalField(max_digits=10, decimal_places=2)
    account_holder_name = models.CharField(max_length=100)
    account_number = models.CharField(max_length=20)
    bank_name = models.CharField(max_length=100)
    status = models.CharField(max_length=10, default='pending')
    date_placed=models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return f"Withdrawal{self.pk}-{self.user.username}"

payments/views.py
from django.shortcuts import render, redirect
from .models import Payment, UserWallet
from django.conf import settings
from django.contrib.auth.decorators import login_required


def initiate_payment(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            amount = request.POST["amount"]
            email = request.POST["email"]
            pk = settings.PAYSTACK_PUBLIC_KEY

            payment = Payment.objects.create(
                amount=amount, email=email, user=request.user
            )
            if int(payment.amount) >= 2000:
                payment.save()

                context = {
                    "payment": payment,
                    "field_values": request.POST,
                    "paystack_pub_key": pk,
                    "amount_value": payment.amount_value(),
                }
                return render(request, "payments/make_payment.html", context)
            else:
                error_message = (
                    "Minimum recharge is 2000. Please enter a correct recharge amount."
                )
                return render(
                    request, "payments/recharge.html", {"error_message": error_message}
                )

        return render(request, "payments/recharge.html")
    else:
        return redirect("/login")


def verifypayment(request, ref):
    payment = Payment.objects.get(ref=ref)
    verified = payment.verifypayment()

    if verified:
        payment.verified = True
        user_wallet = UserWallet.objects.get(user=request.user)
        user_wallet.balance = user_wallet.balance + payment.amount
        user_wallet.save()
        print(request.user.username, " funded wallet successfully")
        return render(request, "payments/success.html")

    return render(request, "payments/success.html")


@login_required
def rechargerec(request):
    rec = Payment.objects.filter(user=request.user, verified=True).order_by(
        "-date_created"
    )
    data = {"rec": rec}
    return render(request, "records/recharge_rec.html", data)

templates/payments/failed.html
<!-- CSS only -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <style>
    * {
      margin: 0%;
      padding: 0%;
      box-sizing: border-box;
    }
    body {
      margin: 0%;
      width: 100%;
      height: fit-content;
      background-color: rgb(255, 255, 255);
    }
  </style>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
    crossorigin="anonymous"
  />
  <!-- JavaScript Bundle with Popper -->
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"
  ></script>

  <div>
    <div>
      <div style="display: flex; align-items: center; flex-direction: column">
        <br /><br /><br />
        <img
          width="50"
          height="50"
          src="https://img.icons8.com/ios/50/ff0000/cancel.png"
          alt="cancel"
        />
        <h2 style="color: #ff0000">Failed</h2>
        <h3>Dear {{ request.user.username }}</h3>
        {%if error_message%}
        <p style="width: 70%;text-align: center;">{{error_message}}</p>
        
        <a href="/products"><button class="btn btn-danger">Back</button></a>
        {%else%}
        <p style="font-size: 20px; color: #5c5c5c">
          transaction failed due to insufficient fund!
        </p>
        <div>
          <a href="/products"><button class="btn btn-danger">Back</button></a>
          <a href="/initiate-payment" class="btn btn-warning"> Recharge </a>
        </div>
        {%endif%}
      </div>
    </div>
  </div>
</html>

templates/payments/make_payment.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
  </head>
  <style>
    * {
      margin: 0%;
      padding: 0%;
      box-sizing: border-box;
    }
    body {
      margin: 0%;
      width: 100%;
      height: fit-content;
    }
  </style>

  <body>
    <a href="/initiate-payment">
      <img
        width="30"
        src="https://img.icons8.com/windows/32/40C057/back.png"
        alt="back"
        style="padding-left: 1%"
      />
    </a>
    
    <div
      style="
        display: flex;
        flex-direction: column;
        font-family: sans-serif;
        font-size: 15px;
        color: rgb(44, 44, 44);
        padding: 2%;
        height: min-content;
        align-items: center;
        border: 5px solid gray;
        padding: 2%;
        border-bottom-left-radius: 30px;
        border-bottom-right-radius: 30px;
      "
    >
      <p style="font-weight: 600">
        You are about to fund your wallet with: {{ payment.amount }}
      </p>

      <img
        width="50"
        height="50"
        src="https://img.icons8.com/ios/50/40C057/buy-for-cash.png"
        alt="buy-for-cash"
      />
      <br />
      <p style="margin: 1%">
        Payment Ref:
        <span style="font-size: 10px; word-wrap: break-word"
          >{{payment.ref}}</span
        >
      </p>
      <button
        style="
          height: 40px;
          background-color: rgb(47, 100, 11);
          border: none;
          border-radius: 10px;
          width: 50%;
          font-family: sans-serif;
          font-size: 20px;
          color: white;
        "
        onclick="payWithPaystack()"
        class="btn btn-primary btn-block mb-4"
        value="Fund"
      >
        <b>Fund</b>
      </button>
    </div>

    <script>
      function payWithPaystack() {
        let currency = "NGN";
        let plan = "";
        let ref = "{{ payment.ref }}";
        let amount = "{{ payment.amount }}";
        let obj = {
          key: "{{ paystack_pub_key }}",
          email: "{{ payment.email }}",
          amount: "{{ amount_value }}",
          ref: ref,
          callback: function (response) {
            window.location.href = "/verify_payment/" + ref;
          },
        };
        if (Boolean(currency)) {
          obj.currency = currency.toUpperCase();
        }
        if (Boolean(plan)) {
          obj.plan - plan;
        }

        var handler = PaystackPop.setup(obj);
        handler.openIframe();
      }
    </script>
  </body>
</html>

templates/payments/recharge.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script>
      // This function takes the button id as a parameter
      function setText(buttonId) {
        // Get the button element by its id
        var button = document.getElementById(buttonId);
        // Get the input element by its id
        var input = document.getElementById("myInput");
        // Get the text from the button's value attribute
        var text = button.value;
        // Set the text to the input's value attribute
        input.value = text;
      }
    </script>
  </head>
  <style>
    * {
      margin: 0%;
      padding: 0%;
      box-sizing: border-box;
    }
    body {
      margin: 0%;
      width: 100%;
      height: fit-content;
      background-color: rgb(244, 244, 244);
    }
    .w {
      margin: 5%;
      font-size: 16px;
      color: rgb(0, 0, 0);
    }
    .user {
      display: flex;
      border: 2px solid gray;
      border-radius: 10px;
      height: fit-content;
      margin-bottom: 2%;
      padding: 2%;
      width: 80%;
      background: white;
    }
    button {
      border: 2px solid rgb(26, 159, 53);
      padding: 2%;
      margin: 1%;
      border-radius: 6px;
      margin-bottom: 20%;
    }
  </style>

  {% if error_message %}
  <a href="/initiate-payment">
    <box-icon name="chevron-left" size="md"></box-icon>
  </a>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
    crossorigin="anonymous"
  />
  <!-- JavaScript Bundle with Popper -->
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"
  ></script>

  <div>
    <div>
      <div style="display: flex; align-items: center; flex-direction: column">
        <br /><br /><br />
        <img
          width="50"
          height="50"
          src="https://img.icons8.com/ios/50/ff0000/cancel.png"
          alt="cancel"
        />
        <p style="font-size: 20px; color: #f80909; text-align: center;width: 60%">
          {{error_message}}
        </p>
        <a href="/initiate-payment" class="btn btn-danger"> Back</a>
      </div>
    </div>
  </div>

  {% else %}
  <div style="display: flex; margin-top: 2%; justify-content: space-between">
    <a href="/dashboard">
      <img
        width="30"
        src="https://img.icons8.com/windows/32/40C057/back.png"
        alt="back"
        style="padding-left: 1%"
      />
    </a>

    <h2 style="padding-right: 6%">Recharge</h2>

    <a href="/rechargerecord" style="padding-right: 3%"
      ><img
        width="25"
        src="https://img.icons8.com/ios/50/40C057/overview-pages-3.png"
        alt="overview-pages-3"
    /></a>
  </div>
  <br /><br /><br />
  <form action="/initiate-payment/" method="POST">
    {% csrf_token %}

    <div style="display: flex; flex-direction: column; align-items: center">
      <div class="user">
        <img
          width="40"
          src="https://img.icons8.com/ios/50/40C057/money--v1.png"
          alt="money--v1"
        />
        <input
          type="number"
          id="myInput"
          placeholder="Enter Amount"
          style="
            height: 40px;
            width: 82%;
            outline: none;
            border: none;
            padding-left: 4%;
            font-size: 20px;
          "
          name="amount"
          required
        />
      </div>

      <div style="width: 100%; display: flex; justify-content: center">
        <button
          id="myButton1"
          value="2000"
          onclick="setText('myButton1'); return false;"
        >
          2000
        </button>
        <button
          id="myButton2"
          value="5000"
          onclick="setText('myButton2'); return false;"
        >
          5000
        </button>
        <button
          id="myButton3"
          value="10000"
          onclick="setText('myButton3'); return false;"
        >
          10000
        </button>
        <button
          id="myButton4"
          value="20000"
          onclick="setText('myButton4'); return false;"
        >
          20000
        </button>
        <button
          id="myButton5"
          value="30000"
          onclick="setText('myButton5'); return false;"
        >
          30000
        </button>
      </div>
    </div>
    <!-- Email input -->

    <label for="email" style="margin-left: 5%"
      >Email <span style="color: red">*</span></label
    >
    <div
      style="
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-between;
      "
    >
      <input
        type="email"
        placeholder="Enter email address"
        style="
          width: 80%;
          height: 40px;
          border: 4px solid rgb(255, 255, 255);
          border-radius: 10px;
          padding-left: 10px;
          font-size: 18px;
        "
        name="email"
        required
        id="email"
      />
    </div>

    <div class="w">
      <h3 style="margin-top: 10%">NB:</h3>
      <p>-Payment would not proceed if email is invalid</p>
      <p>
        -Minimum recharge is 2000, any amount below the minimum recharge would
        not be recieved
      </p>
      <p>-Recharge arrival depends on bank network</p>
      <p>
        -If your recharge has not arrived after 24hours,contact customer service
      </p>
      <br />
    </div>

    <div style="display: flex; justify-content: center">
      <button
        type="submit"
        class="btn btn-primary btn-block mb-4"
        style="
          height: 50px;
          background-color: rgb(47, 100, 11);
          border: none;
          border-radius: 10px;
          width: 50%;
          font-family: sans-serif;
          font-size: 20px;
          color: white;
        "
      >
        Proceed
      </button>
    </div>
  </form>
  {%endif%}
</html>

templates/payments/success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Success</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="container">
      <div class="row text-center">
        <div
          class="style"
          ="display: flex; justify-content: center; flex-direction: column;align-items:center
    "
        >
          <br /><br />
          <img
            width="50"
            src="https://img.icons8.com/ios/50/40C057/approval--v1.png"
            alt="approval--v1"
          />

          <h2 style="color: #0fad00">Success</h2>
          {% if message %}
          <br /><br />
          <h2 style="color: #0fad00">{{ message }}</h2>
          {% endif %}

          <h3>Dear {{ request.user.username }}</h3>
          <p style="font-size: 20px; color: #5c5c5c">Transaction Successful</p>
          <a href="/dashboard" class="btn btn-success">Dashboard</a>
          <br /><br />
        </div>
      </div>
    </div>
  </body>
</html>

templates/payments/withdraw.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
  </head>
  <style>
    * {
      margin: 0%;
      padding: 0%;
      box-sizing: border-box;
    }
    body {
      margin: 0%;
      width: 100%;
      height: fit-content;
      background-color: rgb(244, 244, 244);
    }
    input {
      width: 50%;
      height: 30px;
      border: 2px solid rgb(47, 100, 11);
      border-radius: 20px;

      padding: 2%;
      outline: none;
      position: relative;
      font-size: 15px;
    }
    #id_withdrawal_amount {
      margin-right: 35%;
      margin-bottom: 10%;
      width: 50%;
      height: 40px;
      border-bottom: 6px solid rgb(47, 100, 11);
      border-radius: 10px;
      padding: 2%;
      border-top: 2px solid gray;
      border-left: 2px solid gray;
      border-right: 2px solid gray;
      outline: none;
      font-size: 20px;
      font-family: sans-serif;
      background: #ffffff;
    }
    label #id_withdrawal_amount {
      display: block;
      font-size: 20px;
      font-family: sans-serif;
      padding: 1%;
    }
    label {
      display: inline;
      width: 50%;
      font-size: 15px;
      font-family: sans-serif;
    }
    .w {
      margin: 5%;
      font-size: 16px;
      color: rgb(0, 0, 0);
    }
    p {
      justify-content: space-between;
      display: flex;
      padding-left: 5%;
      padding-right: 5%;
    }
  </style>

  {% if error_message %}
  <div>
    <div>
      <div style="display: flex; align-items: center; flex-direction: column">
        <br /><br /><br />
        <img
          width="50"
          height="50"
          src="https://img.icons8.com/ios/50/ff0000/cancel.png"
          alt="cancel"
        />
        <p
          style="
            font-size: 20px;
            color: #f80909;
            text-align: center;
            width: 70%;
          "
        >
          {{error_message}}
        </p>
        <a href="/withdraw" class="btn btn-danger"> Back</a>
      </div>
    </div>
  </div>

  {% else %}
  <div style="display: flex; margin-top: 2%; justify-content: space-between">
    <a href="/dashboard">
      <img
        width="30"
        src="https://img.icons8.com/windows/32/40C057/back.png"
        alt="back"
        style="padding-left: 1%"
      />
    </a>

    <h2 style="padding-right: 6%">Withdraw</h2>

    <a href="/wrecord" style="padding-right: 3%"
      ><img
        width="25"
        src="https://img.icons8.com/ios/50/40C057/overview-pages-3.png"
        alt="overview-pages-3"
    /></a>
  </div>
  <br />
  <header>
    <div style="display: flex; padding-top: 0%; padding-left: 3%">
      <img
        width="20"
        height="20"
        src="https://img.icons8.com/ios/50/user-male-circle--v1.png"
        alt="user-male-circle--v1"
      />
      <h3 style="font-size: 15px; margin-top: 0.5%">
        <span style="position: relative; bottom: 10%">:</span> {{request.user}}
      </h3>

      {%load static%}
    </div>
    <img
      src="https://thumbs.dreamstime.com/b/man-farmer-icon-holding-rich-harvest-hands-logotype-store-agricultural-products-vegetable-market-natural-organic-91548073.jpg"
      alt=""
      style="width: 15%; border-radius: 50%; margin-left: 10%"
    />
    <div>
      <div style="display: flex">
        <h3
          style="
            margin-top: 1%;
            margin-left: 10%;
            font-size: 20px;
            font-family: Arial, Helvetica, sans-serif;
            font-weight: 600;
          "
        >
          Balance: N{{balance}}
        </h3>
      </div>
    </div>
    <!-- </div> -->
  </header>
  <br /><br />
  <form method="post" action="">
    {% csrf_token %} {{form.as_p}}
    <br /><br />
    <div style="display: flex; justify-content: center">
      <button
        type="submit"
        style="
          height: 40px;
          background-color: rgb(47, 100, 11);
          border: none;
          border-radius: 10px;
          width: 50%;
          font-family: sans-serif;
          font-size: 20px;
          color: white;
        "
      >
        Withdraw
      </button>
    </div>
  </form>

  <div class="w">
    <h3 style="margin-top: 10%">NB:</h3>
    <li>6% bank charges on every withdrawal</li>
    <li>Only users who own machines can withdraw</li>
    <li>Minimum withdrawal is 1000</li>
    <li>Withdrawal arrival depends on bank network</li>
    <li>
      If your withdrawal has not arrived after 24hours,contact customer service
    </li>
  </div>
  <br />
  {%endif%}
</html>